# Generated by Django 2.1.3 on 2018-12-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(default='The address is not specified.', max_length=120),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_name',
            field=models.CharField(default='The place is not specified.', max_length=30),
        ),
    ]
