# Generated by Django 2.1.3 on 2019-01-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190120_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=None),
        ),
    ]
