# Generated by Django 2.1.1 on 2018-10-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20181008_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='host_name',
            field=models.CharField(default='', max_length=160),
        ),
    ]
