# Generated by Django 2.0.1 on 2018-11-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20181109_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='page_id',
            field=models.CharField(default='1ABCDEFGHIJKLMNOPQRSTUVWXYZ5ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ3ABCDEFGHIJKLMNOPQRSTUVWXYZ4', max_length=10, unique=True),
        ),
    ]
