# Generated by Django 2.0.1 on 2018-11-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20181114_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='page_id',
            field=models.CharField(default='ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ3ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ286', max_length=100, unique=True),
        ),
    ]
