# Generated by Django 2.0.1 on 2018-11-18 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20181114_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='page_id',
        ),
    ]
