# Generated by Django 2.0.1 on 2018-11-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_remove_event_page_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_id',
            field=models.CharField(default='XXXXXXXXXX', max_length=10),
        ),
    ]
