# Generated by Django 2.0.1 on 2018-11-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_event_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.CharField(default='XXXXXXXXXX', max_length=10, unique=True),
        ),
    ]
