# Generated by Django 2.0.1 on 2018-11-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20181122_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='language',
            field=models.CharField(default='Any language', max_length=50),
        ),
    ]
