# Generated by Django 2.0.1 on 2018-11-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_event_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
    ]
