# Generated by Django 2.0.1 on 2018-11-23 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20181123_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
    ]
