# Generated by Django 2.0.1 on 2018-11-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_event_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='picture',
            field=models.ImageField(default='place_holders/place_holder_700x400', upload_to='event_images/'),
        ),
    ]
