# Generated by Django 2.1.3 on 2018-11-26 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_auto_20181125_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='picture',
            new_name='image',
        ),
    ]
