# Generated by Django 2.1.3 on 2018-12-21 09:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_join_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='join_list',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
