# Generated by Django 2.1.3 on 2019-01-29 00:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190128_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hangouts_to_join',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='watch_list',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
    ]
