# Generated by Django 2.1.3 on 2018-12-21 10:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181221_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='joined_hangouts',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
