# Generated by Django 2.1.3 on 2019-06-02 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_hangouts_to_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='hangouts_to_host',
            new_name='hosting_list',
        ),
    ]
